/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients/index'
import { Route as AuthenticatedEncountersIndexRouteImport } from './routes/_authenticated/encounters/index'
import { Route as AuthenticatedCatalogsIndexRouteImport } from './routes/_authenticated/catalogs/index'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients/$patientId'
import { Route as AuthenticatedFacilitiesSitesRouteImport } from './routes/_authenticated/facilities/sites'
import { Route as AuthenticatedFacilitiesServiceUnitsRouteImport } from './routes/_authenticated/facilities/service-units'
import { Route as AuthenticatedFacilitiesPractitionersRouteImport } from './routes/_authenticated/facilities/practitioners'
import { Route as AuthenticatedFacilitiesOrganizationsRouteImport } from './routes/_authenticated/facilities/organizations'
import { Route as AuthenticatedEncountersEncounterIdRouteImport } from './routes/_authenticated/encounters/$encounterId'
import { Route as AuthenticatedCatalogsTableNameRouteImport } from './routes/_authenticated/catalogs/$tableName'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEncountersIndexRoute =
  AuthenticatedEncountersIndexRouteImport.update({
    id: '/encounters/',
    path: '/encounters/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogsIndexRoute =
  AuthenticatedCatalogsIndexRouteImport.update({
    id: '/catalogs/',
    path: '/catalogs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacilitiesSitesRoute =
  AuthenticatedFacilitiesSitesRouteImport.update({
    id: '/facilities/sites',
    path: '/facilities/sites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacilitiesServiceUnitsRoute =
  AuthenticatedFacilitiesServiceUnitsRouteImport.update({
    id: '/facilities/service-units',
    path: '/facilities/service-units',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacilitiesPractitionersRoute =
  AuthenticatedFacilitiesPractitionersRouteImport.update({
    id: '/facilities/practitioners',
    path: '/facilities/practitioners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacilitiesOrganizationsRoute =
  AuthenticatedFacilitiesOrganizationsRouteImport.update({
    id: '/facilities/organizations',
    path: '/facilities/organizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEncountersEncounterIdRoute =
  AuthenticatedEncountersEncounterIdRouteImport.update({
    id: '/encounters/$encounterId',
    path: '/encounters/$encounterId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogsTableNameRoute =
  AuthenticatedCatalogsTableNameRouteImport.update({
    id: '/catalogs/$tableName',
    path: '/catalogs/$tableName',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/catalogs/$tableName': typeof AuthenticatedCatalogsTableNameRoute
  '/encounters/$encounterId': typeof AuthenticatedEncountersEncounterIdRoute
  '/facilities/organizations': typeof AuthenticatedFacilitiesOrganizationsRoute
  '/facilities/practitioners': typeof AuthenticatedFacilitiesPractitionersRoute
  '/facilities/service-units': typeof AuthenticatedFacilitiesServiceUnitsRoute
  '/facilities/sites': typeof AuthenticatedFacilitiesSitesRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/catalogs/': typeof AuthenticatedCatalogsIndexRoute
  '/encounters/': typeof AuthenticatedEncountersIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/catalogs/$tableName': typeof AuthenticatedCatalogsTableNameRoute
  '/encounters/$encounterId': typeof AuthenticatedEncountersEncounterIdRoute
  '/facilities/organizations': typeof AuthenticatedFacilitiesOrganizationsRoute
  '/facilities/practitioners': typeof AuthenticatedFacilitiesPractitionersRoute
  '/facilities/service-units': typeof AuthenticatedFacilitiesServiceUnitsRoute
  '/facilities/sites': typeof AuthenticatedFacilitiesSitesRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/catalogs': typeof AuthenticatedCatalogsIndexRoute
  '/encounters': typeof AuthenticatedEncountersIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/catalogs/$tableName': typeof AuthenticatedCatalogsTableNameRoute
  '/_authenticated/encounters/$encounterId': typeof AuthenticatedEncountersEncounterIdRoute
  '/_authenticated/facilities/organizations': typeof AuthenticatedFacilitiesOrganizationsRoute
  '/_authenticated/facilities/practitioners': typeof AuthenticatedFacilitiesPractitionersRoute
  '/_authenticated/facilities/service-units': typeof AuthenticatedFacilitiesServiceUnitsRoute
  '/_authenticated/facilities/sites': typeof AuthenticatedFacilitiesSitesRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/catalogs/': typeof AuthenticatedCatalogsIndexRoute
  '/_authenticated/encounters/': typeof AuthenticatedEncountersIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/users'
    | '/catalogs/$tableName'
    | '/encounters/$encounterId'
    | '/facilities/organizations'
    | '/facilities/practitioners'
    | '/facilities/service-units'
    | '/facilities/sites'
    | '/patients/$patientId'
    | '/catalogs/'
    | '/encounters/'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/admin/users'
    | '/catalogs/$tableName'
    | '/encounters/$encounterId'
    | '/facilities/organizations'
    | '/facilities/practitioners'
    | '/facilities/service-units'
    | '/facilities/sites'
    | '/patients/$patientId'
    | '/catalogs'
    | '/encounters'
    | '/patients'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/admin/users'
    | '/_authenticated/catalogs/$tableName'
    | '/_authenticated/encounters/$encounterId'
    | '/_authenticated/facilities/organizations'
    | '/_authenticated/facilities/practitioners'
    | '/_authenticated/facilities/service-units'
    | '/_authenticated/facilities/sites'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/catalogs/'
    | '/_authenticated/encounters/'
    | '/_authenticated/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/encounters/': {
      id: '/_authenticated/encounters/'
      path: '/encounters'
      fullPath: '/encounters/'
      preLoaderRoute: typeof AuthenticatedEncountersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogs/': {
      id: '/_authenticated/catalogs/'
      path: '/catalogs'
      fullPath: '/catalogs/'
      preLoaderRoute: typeof AuthenticatedCatalogsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facilities/sites': {
      id: '/_authenticated/facilities/sites'
      path: '/facilities/sites'
      fullPath: '/facilities/sites'
      preLoaderRoute: typeof AuthenticatedFacilitiesSitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facilities/service-units': {
      id: '/_authenticated/facilities/service-units'
      path: '/facilities/service-units'
      fullPath: '/facilities/service-units'
      preLoaderRoute: typeof AuthenticatedFacilitiesServiceUnitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facilities/practitioners': {
      id: '/_authenticated/facilities/practitioners'
      path: '/facilities/practitioners'
      fullPath: '/facilities/practitioners'
      preLoaderRoute: typeof AuthenticatedFacilitiesPractitionersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facilities/organizations': {
      id: '/_authenticated/facilities/organizations'
      path: '/facilities/organizations'
      fullPath: '/facilities/organizations'
      preLoaderRoute: typeof AuthenticatedFacilitiesOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/encounters/$encounterId': {
      id: '/_authenticated/encounters/$encounterId'
      path: '/encounters/$encounterId'
      fullPath: '/encounters/$encounterId'
      preLoaderRoute: typeof AuthenticatedEncountersEncounterIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogs/$tableName': {
      id: '/_authenticated/catalogs/$tableName'
      path: '/catalogs/$tableName'
      fullPath: '/catalogs/$tableName'
      preLoaderRoute: typeof AuthenticatedCatalogsTableNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCatalogsTableNameRoute: typeof AuthenticatedCatalogsTableNameRoute
  AuthenticatedEncountersEncounterIdRoute: typeof AuthenticatedEncountersEncounterIdRoute
  AuthenticatedFacilitiesOrganizationsRoute: typeof AuthenticatedFacilitiesOrganizationsRoute
  AuthenticatedFacilitiesPractitionersRoute: typeof AuthenticatedFacilitiesPractitionersRoute
  AuthenticatedFacilitiesServiceUnitsRoute: typeof AuthenticatedFacilitiesServiceUnitsRoute
  AuthenticatedFacilitiesSitesRoute: typeof AuthenticatedFacilitiesSitesRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedCatalogsIndexRoute: typeof AuthenticatedCatalogsIndexRoute
  AuthenticatedEncountersIndexRoute: typeof AuthenticatedEncountersIndexRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCatalogsTableNameRoute: AuthenticatedCatalogsTableNameRoute,
  AuthenticatedEncountersEncounterIdRoute:
    AuthenticatedEncountersEncounterIdRoute,
  AuthenticatedFacilitiesOrganizationsRoute:
    AuthenticatedFacilitiesOrganizationsRoute,
  AuthenticatedFacilitiesPractitionersRoute:
    AuthenticatedFacilitiesPractitionersRoute,
  AuthenticatedFacilitiesServiceUnitsRoute:
    AuthenticatedFacilitiesServiceUnitsRoute,
  AuthenticatedFacilitiesSitesRoute: AuthenticatedFacilitiesSitesRoute,
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedCatalogsIndexRoute: AuthenticatedCatalogsIndexRoute,
  AuthenticatedEncountersIndexRoute: AuthenticatedEncountersIndexRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
